### DISCUSSION TITLE
Iskratel Si3000 echo consisting of ANSI characters only

### DISCUSSION THREAD

**Discussion by denisbondar** [carlmontanari/scrapli#313] [Q&A] [answered]
Hey, everybody!
How to deal with devices like the Iskratel SI3000 optical line terminal, which in response to input characters returns a horrible echo in the form of ANSI characters. For example (scrapli transmits a command `configure` and the device returns this ANSI sequence):
```
\e7c\e8\e7o\e8\e7n\e8\e7f\e8\e7i\e8\e7g\e8\e7u\e8\e7r\e8\e\7e\e8
```

Well, what happens if you enter the command manually in Telnet terminal and watch the exchange with Wireshark (below I show the character-by-character entry of the command > and what the device < responds):
```
> c
< \x1B7c\x1B8\x1B[1C

> o
< \x1B7o\x1B8\x1B[1C

> n
< \x1B7n\x1B8\x1B[1C

> f
< \x1B7f\x1B8\x1B[1C

> i
< \x1B7i\x1B8\x1B[1C

> g
< \x1B7g\x1B8\x1B[1C

> u
< \x1B7u\x1B8\x1B[1C

> r
< \x1B7r\x1B8\x1B[1C

> e
< \x1B7e\x1B8\x1B[1C
```
(Somehow I didn't think it would be better to take a shorter command for the demo.)

In general, I get this echo response to any information sent towards the device.

Naturally, the scrapli algorithms do not see in the response what they sent to the device, and nothing works.

**How can I solve this problem, considering that I need the functionality of a network driver in this case?**

**Comment by carlmontanari** [comment]
damn @denisbondar always coming in hot with some wild ones 😁 !!

am I understanding correctly that this is happening on *write* -- and thats why scrapli never thinks the command it sent is actually there/done? if "yes", this could probably be solved the same way we did in scrapligo [here](https://github.com/scrapli/scrapligo/blob/main/util/bytes.go#L53-L84) -- I just never got around o bringing it into scrapli(py). If we bring this to scrapli(py) (which I am super down to do) we just gotta make sure its not super slow since it very well could be... if it is we could make it optional perhaps.

Lemme know if I misread that or if I'm tracking correctly and we can figure out what to do. thanks for bringing this up @denisbondar !

**Reply by denisbondar** [reply]
As an "head-on" solution option. Maybe add some option to disable checking of the passed command via echo?

**Reply by denisbondar** [reply]
This is the [Channel.send_input()](https://github.com/carlmontanari/scrapli/blob/main/scrapli/channel/sync_channel.py#L488) method, which calls [_read_until_input()](https://github.com/carlmontanari/scrapli/blob/main/scrapli/channel/sync_channel.py#L109) to wait for a match between the command sent and the text returned from the device.

Channel creation is hard-coded in the [Driver initialization](https://github.com/carlmontanari/scrapli/blob/main/scrapli/driver/base/sync_driver.py#L23) and it is not possible to use its alternative implementation.

Maybe an additional ansi escape cleanup can be added [at this point](https://github.com/carlmontanari/scrapli/blob/main/scrapli/channel/sync_channel.py#L109) so that it fits the case describing too?

**Comment by carlmontanari** [comment]
> Maybe add some option to disable checking of the passed command via echo?

yeah that's possible for sure. does the prompt come back "nicely" after entering the input? or is there more ansi craziness in the prompt output too? an `eager_input` option or something [here](https://github.com/carlmontanari/scrapli/blob/614a6d9bb9fb3b54c8808c4c93246308c75a2263/scrapli/channel/sync_channel.py#L488) seems like it would be reasonable, ya?

> not possible to use its alternative implementation 

you could get crazy with `types.MethodType` 🤣 but I get what you mean 😄 

> Maybe an additional ansi escape cleanup can be added [at this point](https://github.com/carlmontanari/scrapli/blob/main/scrapli/channel/sync_channel.py#L109) so that it fits the case describing too?

yeah, ideally I don't wanna play whack-a-mole with ansi patterns for forever. do you know what the deal is with these ansi patterns and why our regex doesn't catch them?


so yeah - sounds like we have a few things to do:

1. add the fuzzy read until like scrapligo
2. add something like an eager_input flag for send stuff here
3. maybe expand ansi pattern

**Reply by denisbondar** [reply]
> yeah that's possible for sure. does the prompt come back "nicely" after entering the input? or is there more ansi craziness in the prompt output too?

The prompt looks normal. So far I've only noticed a problem with echo.
I'd rather show an example of scrapli_replay

```yaml
x.x.x.x:23:TelnetTransport::0:
  connection_profile: {auth_bypass: false, auth_password: true, auth_private_key: '',
    auth_private_key_passphrase: false, auth_secondary: false, auth_username: admin,
    host: x.x.x.x, port: 23, transport: telnet}
  interactions:
    - {channel_output: "\x01\x06\nLinux 4.14.140-lsp-1.1.212-0 (Iskratel) (pts/2)\n
        \n(none) login: ", expected_channel_input: admin, expected_channel_input_redacted: false}
    - {channel_output: '', expected_channel_input: "\r\n", expected_channel_input_redacted: false}
    - {channel_output: "admin\nPassword:", expected_channel_input: REDACTED, expected_channel_input_redacted: true}
    - {channel_output: '', expected_channel_input: "\r\n", expected_channel_input_redacted: false}
    - {channel_output: "\n\t\t\t**************************\n\t\t\t*              \
        \          *\n\t\t\t*  Iskratel CLI Engine   *\n\t\t\t*      version 1.0 \
        \      *\n\t\t\t*                        *\n\t\t\t**************************\n
        Iskratel switching #", expected_channel_input: "\r\n", expected_channel_input_redacted: false}
    - {channel_output: "\nIskratel switching #", expected_channel_input: "\r\n", expected_channel_input_redacted: false}
    - {channel_output: "\nIskratel switching #", expected_channel_input: configure,
      expected_channel_input_redacted: false}
    - {channel_output: "\e7c\e8\e7o\e8\e7n\e8\e7f\e8\e7i\e8\e7g\e8\e7u\e8\e7r\e8\e\
        7e\e8", expected_channel_input: null, expected_channel_input_redacted: false}
```

> do you know what the deal is with these ansi patterns and why our regex doesn't catch them?

I don't know much about ANSI ESC codes. But I noticed that I get three bytes in echo for every character sent to the device. For example, on after transmitting the character "c", I get the response: `\x1B7c\x1B8\x1B[1C`, of which there is no "c" character. The last character of this sequence is removed by a regular expression in the _read_until_input method, as I wrote above. And we get the remaining two: `\x1B7c\x1B8` or `\e7c\e8`. Although we expect the "c" character.
So we can't just use a regular expression.

UPD: Although, of course, in the _read_until_input metda, we can add the removal of the sequence \x1B7 and \x1B8 from the buffer [to the already existing filter](https://github.com/carlmontanari/scrapli/blob/e02100d6438028c895482b5eb58e21040887282c/scrapli/channel/sync_channel.py#L109).

UPD2: Or add these sequences to the ESC filter I once supplemented #302. If this filter is used globally. I don't remember that, unfortunately.
